# Generated by Django 5.0.1 on 2024-01-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
